<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitf9a12ba891c49caec1f1a632823dfbe6
{
    public static $files = array (
        'c65d09b6820da036953a371c8c73a9b1' => __DIR__ . '/..' . '/facebook/graph-sdk/src/Facebook/polyfills.php',
    );

    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Facebook\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Facebook\\' => 
        array (
            0 => __DIR__ . '/..' . '/facebook/graph-sdk/src/Facebook',
        ),
    );

    public static $prefixesPsr0 = array (
        'o' => 
        array (
            'org\\bovigo\\vfs' => 
            array (
                0 => __DIR__ . '/..' . '/mikey179/vfsStream/src/main/php',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitf9a12ba891c49caec1f1a632823dfbe6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitf9a12ba891c49caec1f1a632823dfbe6::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitf9a12ba891c49caec1f1a632823dfbe6::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
